#!/usr/bin/env bash
# list-custom-apps.sh
# Finds all custom applications installed via various package managers.
# =====================
# Generated by AI, doesn't really work 100% accurately, but I'm sure there is some scripting knowledge here
# =====================
# Output: deps.txt in the repo root (script's parent directory)

set -euo pipefail

OUTPUT_FILE="$(cd "$(dirname "$0")/.." && pwd)/deps.txt"

# Temp file to collect all entries before sorting
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

add_entry() {
  local origin="$1"
  local name="$2"
  local path="$3"
  printf "%-20s %-40s %s\n" "$origin" "$name" "$path" >> "$TMP"
}

header() {
  echo ""
  echo "=== $1 ==="
}

# ---------------------------------------------------------------------------
# Homebrew (Linuxbrew)
# ---------------------------------------------------------------------------
if command -v brew &>/dev/null; then
  BREW_BIN="$(brew --prefix)/bin"
  BREW_SBIN="$(brew --prefix)/sbin"
  while IFS= read -r pkg; do
    # brew list --formula gives package names; find their binaries
    for bin_dir in "$BREW_BIN" "$BREW_SBIN"; do
      # Each formula may install multiple binaries; find ones that belong to it
      if [[ -d "$(brew --prefix)/Cellar/$pkg" ]]; then
        while IFS= read -r f; do
          [[ -x "$f" ]] && add_entry "brew" "$pkg" "$f"
        done < <(find "$(brew --prefix)/Cellar/$pkg" -type f -perm /111 2>/dev/null | grep -E '/bin/[^/]+$' | sort -u)
      fi
    done
  done < <(brew list --formula 2>/dev/null)

  # Casks (GUI apps)
  while IFS= read -r cask; do
    add_entry "brew-cask" "$cask" "(GUI app)"
  done < <(brew list --cask 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# Cargo (Rust)
# ---------------------------------------------------------------------------
CARGO_BIN="${CARGO_HOME:-$HOME/.cargo}/bin"
# Also check /work/.cargo which was found on this system
for cargo_bin in "$CARGO_BIN" "/work/.cargo/bin"; do
  if [[ -d "$cargo_bin" ]]; then
    while IFS= read -r f; do
      name="$(basename "$f")"
      add_entry "cargo" "$name" "$f"
    done < <(find "$cargo_bin" -maxdepth 1 -type f -perm /111 2>/dev/null)
  fi
done

# ---------------------------------------------------------------------------
# Volta (Node.js toolchain manager)
# ---------------------------------------------------------------------------
VOLTA_BIN="$HOME/.volta/bin"
if [[ -d "$VOLTA_BIN" ]]; then
  while IFS= read -r f; do
    name="$(basename "$f")"
    add_entry "volta" "$name" "$f"
  done < <(find "$VOLTA_BIN" -maxdepth 1 -type f -perm /111 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# Bun (JS runtime & package manager)
# ---------------------------------------------------------------------------
BUN_BIN="${BUN_INSTALL:-$HOME/.bun}/bin"
if [[ -d "$BUN_BIN" ]]; then
  while IFS= read -r f; do
    name="$(basename "$f")"
    add_entry "bun" "$name" "$f"
  done < <(find "$BUN_BIN" -maxdepth 1 -type f -o -maxdepth 1 -type l 2>/dev/null | xargs -I{} sh -c 'test -x "{}" && echo "{}"')
fi

# ---------------------------------------------------------------------------
# DVM / Deno
# ---------------------------------------------------------------------------
DVM_BIN="${DVM_DIR:-$HOME/.dvm}/bin"
if [[ -d "$DVM_BIN" ]]; then
  while IFS= read -r f; do
    name="$(basename "$f")"
    add_entry "dvm" "$name" "$f"
  done < <(find "$DVM_BIN" -maxdepth 1 \( -type f -o -type l \) -perm /111 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# Go binaries (installed via go install)
# ---------------------------------------------------------------------------
GOPATH="${GOPATH:-$HOME/go}"
# Also check the dotfiles-configured GOPATH
for gobin in "$GOPATH/bin" "$HOME/dev/go/bin"; do
  if [[ -d "$gobin" ]]; then
    while IFS= read -r f; do
      name="$(basename "$f")"
      add_entry "go-install" "$name" "$f"
    done < <(find "$gobin" -maxdepth 1 -type f -perm /111 2>/dev/null)
  fi
done

# ---------------------------------------------------------------------------
# pyenv (Python version manager)
# ---------------------------------------------------------------------------
PYENV_ROOT="${PYENV_ROOT:-$HOME/.pyenv}"
if [[ -x "$PYENV_ROOT/bin/pyenv" ]]; then
  # pyenv itself
  add_entry "binary" "pyenv" "$PYENV_ROOT/bin/pyenv"

  # List installed Python versions
  while IFS= read -r ver; do
    ver="$(echo "$ver" | tr -d ' *')"
    [[ -z "$ver" || "$ver" == "system" ]] && continue
    py_bin="$PYENV_ROOT/versions/$ver/bin/python"
    [[ -x "$py_bin" ]] && add_entry "pyenv" "python@$ver" "$py_bin"
  done < <("$PYENV_ROOT/bin/pyenv" versions 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# pip / pip3 user-installed packages
# ---------------------------------------------------------------------------
for pip_cmd in pip pip3; do
  if command -v "$pip_cmd" &>/dev/null; then
    while IFS= read -r line; do
      pkg="$(echo "$line" | awk '{print $1}')"
      # Find the binary in user's local bin
      bin_path="$(command -v "$pkg" 2>/dev/null || true)"
      if [[ -n "$bin_path" ]]; then
        add_entry "$pip_cmd" "$pkg" "$bin_path"
      else
        add_entry "$pip_cmd" "$pkg" "(no binary)"
      fi
    done < <("$pip_cmd" list --user 2>/dev/null | tail -n +3)
    break  # Only run once (pip and pip3 are usually the same)
  fi
done

# ---------------------------------------------------------------------------
# uv (Python package/tool manager)
# ---------------------------------------------------------------------------
UV_BIN="$HOME/.local/bin"
if command -v uv &>/dev/null; then
  add_entry "binary" "uv" "$(command -v uv)"
  # uv tool list
  while IFS= read -r line; do
    pkg="$(echo "$line" | awk '{print $1}')"
    [[ -z "$pkg" || "$pkg" == "-" ]] && continue
    bin_path="$(command -v "$pkg" 2>/dev/null || true)"
    add_entry "uv" "$pkg" "${bin_path:-(no binary)}"
  done < <(uv tool list 2>/dev/null | tail -n +1)
fi

# ---------------------------------------------------------------------------
# snap
# ---------------------------------------------------------------------------
if command -v snap &>/dev/null; then
  # Skip base/runtime snaps - only list real apps
  while IFS= read -r line; do
    name="$(echo "$line" | awk '{print $1}')"
    [[ -z "$name" || "$name" == "Name" ]] && continue
    # Skip known base/runtime snaps
    case "$name" in
      bare|core*|gnome-*|gtk-common-themes|mesa-*|snap-store|snapd*) continue ;;
    esac
    snap_bin="/snap/bin/$name"
    [[ ! -e "$snap_bin" ]] && snap_bin="(snap app)"
    add_entry "snap" "$name" "$snap_bin"
  done < <(snap list 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# flatpak
# ---------------------------------------------------------------------------
if command -v flatpak &>/dev/null; then
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    app_id="$(echo "$line" | awk '{print $2}')"
    name="$(echo "$line" | awk '{print $1}')"
    add_entry "flatpak" "${name:-$app_id}" "(flatpak: $app_id)"
  done < <(flatpak list --app --columns=name,application 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# apt / dpkg manually-installed packages (not dependencies of other packages)
# ---------------------------------------------------------------------------
if command -v apt-mark &>/dev/null; then
  while IFS= read -r pkg; do
    [[ -z "$pkg" ]] && continue
    # Find the main binary (heuristic: look for /usr/bin/<pkg> or similar)
    bin_path="$(command -v "$pkg" 2>/dev/null || true)"
    add_entry "apt" "$pkg" "${bin_path:-(system package)}"
  done < <(apt-mark showmanual 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# ~/.local/bin — binaries installed manually or by tools like pip/uv
# ---------------------------------------------------------------------------
LOCAL_BIN="$HOME/.local/bin"
if [[ -d "$LOCAL_BIN" ]]; then
  while IFS= read -r f; do
    name="$(basename "$f")"
    # Check if already covered by another package manager
    if ! grep -qF "$f" "$TMP" 2>/dev/null; then
      add_entry "binary" "$name" "$f"
    fi
  done < <(find "$LOCAL_BIN" -maxdepth 1 \( -type f -o -type l \) -perm /111 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# /usr/local/bin — binaries installed directly (not via apt)
# ---------------------------------------------------------------------------
if [[ -d /usr/local/bin ]]; then
  while IFS= read -r f; do
    name="$(basename "$f")"
    # Skip if managed by apt (symlinks owned by a package)
    if command -v dpkg &>/dev/null && dpkg -S "$f" &>/dev/null 2>&1; then
      continue
    fi
    if ! grep -qF "$f" "$TMP" 2>/dev/null; then
      add_entry "binary" "$name" "$f"
    fi
  done < <(find /usr/local/bin -maxdepth 1 \( -type f -o -type l \) -perm /111 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# ~/bin — personal scripts/binaries
# ---------------------------------------------------------------------------
if [[ -d "$HOME/bin" ]]; then
  while IFS= read -r f; do
    name="$(basename "$f")"
    if ! grep -qF "$f" "$TMP" 2>/dev/null; then
      add_entry "binary" "$name" "$f"
    fi
  done < <(find "$HOME/bin" -maxdepth 1 \( -type f -o -type l \) -perm /111 2>/dev/null)
fi

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
{
  echo "Custom installed applications — generated $(date)"
  echo ""
  printf "%-20s %-40s %s\n" "ORIGIN" "NAME" "PATH"
  printf "%-20s %-40s %s\n" "--------------------" "----------------------------------------" "--------------------"
  # Sort by origin, then name
  sort -u -k1,1 -k2,2 "$TMP"
} > "$OUTPUT_FILE"

echo "Done. Results written to: $OUTPUT_FILE"
echo "Total entries: $(wc -l < "$TMP")"
