#!/usr/bin/env bash
#
# Apply a stored display layout for whichever external monitor is connected.
#
# Monitors are matched on EDID rather than on connector name: every HDMI screen
# shows up as the same connector, so the connector alone cannot tell one monitor
# from another. Bytes 8-11 of the EDID (manufacturer id + product code) identify
# the model, which is the granularity we want -- two units of the same model get
# the same layout.
#
# Profiles live in ~/.config/i3/monitors/*.conf, one per monitor. i3 runs this on
# startup and reload; run it by hand to see what it detected.

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/monitors.sh
. "$script_dir/lib/monitors.sh"

profile_dir="${XDG_CONFIG_HOME:-$HOME/.config}/i3/monitors"

# Fonts cannot be set over IPC: i3's parser takes no `font` command, and `bar`
# accepts only hidden_state/mode. A bar's font is settable only inside its own
# bar block, so per-screen sizes mean per-screen blocks -- the bars are therefore
# generated here rather than declared in the main config, which also binds each
# one to an output actually detected. The fragment is included by the main config
# and picked up with a reload. It lives outside the repo so that docking does not
# dirty the working tree.
generated_config="${XDG_CACHE_HOME:-$HOME/.cache}/i3/monitor-display.conf"

bar_position="top"
bar_status_command="i3status"

# Used when no profile matches: the internal panel is HiDPI, so it wants a
# larger size than a big external screen does.
default_font_family="DejaVu Sans Mono"
default_font_size="10"

log() { printf '[monitor-profile] %s\n' "$*" >&2; }

# One "<output>|<family>|<size>" per bar, collected while the layout is decided.
bar_specs=()

emit_config() {
	local spec output family size

	printf '# Generated by apply-monitor-profile.sh -- edit the monitor profile instead.\n'
	printf 'font pango:%s %s\n' "$font_family" "$font_size"

	for spec in "${bar_specs[@]:-}"; do
		[ -n "$spec" ] || continue
		IFS='|' read -r output family size <<<"$spec"
		printf '\nbar {\n        output %s\n        position %s\n        status_command %s\n        font pango:%s %s\n}\n' \
			"$output" "$bar_position" "$bar_status_command" "$family" "$size"
	done
}

# Rewrite only when something actually changed: a reload restarts i3bar and the
# status command, which is worth skipping when nothing moved.
apply_config() {
	local tmp
	tmp="$(mktemp)"
	emit_config >"$tmp"

	if cmp -s "$tmp" "$generated_config"; then
		rm -f "$tmp"
		log "bars and font already current"
		return 0
	fi

	mkdir -p "$(dirname "$generated_config")"
	mv "$tmp" "$generated_config"
	chmod 0644 "$generated_config"

	if i3-msg -t get_version >/dev/null 2>&1; then
		i3-msg reload >/dev/null
		log "reloaded i3 with updated bars and font"
	else
		log "i3 not running; bars and font apply on next start"
	fi
}

# Profiles declare their own EDID_ID, so files stay named after the monitor.
find_profile() {
	local id="$1" file
	for file in "$profile_dir"/*.conf; do
		[ -e "$file" ] || continue
		if [ "$(. "$file"; printf '%s' "${EDID_ID:-}")" = "$id" ]; then
			printf '%s' "$file"
			return 0
		fi
	done
	return 1
}

laptop=""
externals=()

while read -r output edid; do
	[ -n "${edid:-}" ] || continue
	case "$output" in
		eDP*|LVDS*) laptop="$output" ;;
		*) externals+=("$output:$(edid_model_id "$edid")") ;;
	esac
done < <(read_outputs)

if [ -z "$laptop" ]; then
	log "no internal panel found; leaving displays untouched"
	exit 0
fi

# Pick the first external we have a profile for. Once a profile applies it owns
# the layout, so any further screens are switched off rather than left to
# displace it; with no profile at all they are extended instead (see below).
external=""
profile=""
unused=()

for entry in "${externals[@]}"; do
	output="${entry%%:*}"
	id="${entry##*:}"
	if [ -z "$external" ] && profile="$(find_profile "$id")"; then
		external="$output"
	else
		log "no profile for $output (EDID id $id)"
		unused+=("$output")
	fi
done

xrandr_args=()

if [ -z "$external" ]; then
	# Nothing recognised. Rather than blank an unknown screen, extend it at its
	# preferred mode -- the log line above carries the id needed for a profile.
	log "no profile matched; extending unknown outputs from $laptop"
	font_family="$default_font_family"
	font_size="$default_font_size"
	xrandr_args+=(--output "$laptop" --auto --primary --pos 0x0 --rotate normal)
	bar_specs+=("$laptop|$font_family|$font_size")
	previous="$laptop"
	for output in "${unused[@]:-}"; do
		[ -n "$output" ] || continue
		xrandr_args+=(--output "$output" --auto --right-of "$previous")
		bar_specs+=("$output|$font_family|$font_size")
		previous="$output"
	done
	unused=()
else
	# shellcheck source=/dev/null
	. "$profile"

	: "${NAME:=$external}"
	: "${MODE:?profile $profile must set MODE}"
	: "${POSITION:=0x0}"
	: "${LAPTOP_MODE:=1920x1080}"
	# No laptop position means nothing to place it by, so it stays dark.
	: "${LAPTOP_POSITION:=off}"
	: "${FONT_FAMILY:=$default_font_family}"
	: "${FONT_SIZE:=$default_font_size}"
	# Each bar defaults to the window-title size, so a profile only names the
	# ones that need to differ -- typically the HiDPI laptop against a big,
	# coarse external panel.
	: "${BAR_FONT_SIZE:=$FONT_SIZE}"
	: "${LAPTOP_BAR_FONT_SIZE:=$FONT_SIZE}"

	font_family="$FONT_FAMILY"
	font_size="$FONT_SIZE"

	# Positions are stored, not derived: whatever was saved is what gets applied.
	read -r ext_x ext_y < <(parse_position "$POSITION") ||
		{ log "POSITION '$POSITION' in $profile is not <X>x<Y>"; exit 1; }

	log "$NAME on $external: $MODE at $POSITION"

	bar_specs+=("$external|$FONT_FAMILY|$BAR_FONT_SIZE")
	xrandr_args+=(--output "$external" --mode "$MODE" --pos "$POSITION" --rotate normal --primary)
	[ -n "${RATE:-}" ] && xrandr_args+=(--rate "$RATE")

	if [ "$LAPTOP_POSITION" = off ]; then
		log "laptop off"
		xrandr_args+=(--output "$laptop" --off)
	else
		read -r lap_x lap_y < <(parse_position "$LAPTOP_POSITION") ||
			{ log "LAPTOP_POSITION '$LAPTOP_POSITION' in $profile is not <X>x<Y>"; exit 1; }

		log "laptop at $LAPTOP_POSITION -- $(describe_placement \
			"$ext_x" "$ext_y" "$(mode_width "$MODE")" "$(mode_height "$MODE")" \
			"$lap_x" "$lap_y" "$(mode_width "$LAPTOP_MODE")" "$(mode_height "$LAPTOP_MODE")")"

		bar_specs+=("$laptop|$FONT_FAMILY|$LAPTOP_BAR_FONT_SIZE")
		xrandr_args+=(--output "$laptop" --mode "$LAPTOP_MODE" --pos "$LAPTOP_POSITION" --rotate normal)
		[ -n "${LAPTOP_RATE:-}" ] && xrandr_args+=(--rate "$LAPTOP_RATE")
	fi

	log "bar fonts: $external ${BAR_FONT_SIZE}pt, $laptop ${LAPTOP_BAR_FONT_SIZE}pt"
fi

for output in "${unused[@]:-}"; do
	[ -n "$output" ] || continue
	xrandr_args+=(--output "$output" --off)
done

xrandr "${xrandr_args[@]}"

apply_config
