volumes:
  mongo-data-1:

services:
  mongo:
    image: mongodb/mongodb-community-server:${MONGODB_VERSION:-7.0}-ubi8
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongo}
    volumes:
      - mongo-data-1:/data/db
    entrypoint: |
      bash -c
        "mongod --replSet $$MONGODB_REPLICA_SET_NAME --bind_ip_all &
          sleep 2;
          until mongosh --eval \"db.adminCommand('ping')\"; do
            echo '=====> Waiting for Mongo...';
            sleep 1;
          done;
          echo \"=====> Initiating ReplSet $$MONGODB_REPLICA_SET_NAME at $$MONGODB_INITIAL_PRIMARY_HOST:$$MONGODB_PORT_NUMBER...\";
          mongosh --eval \"rs.initiate({_id: '$$MONGODB_REPLICA_SET_NAME', members: [{ _id: 0, host: '$$MONGODB_INITIAL_PRIMARY_HOST:$$MONGODB_PORT_NUMBER' }]})\";
          echo '=====> Initiating ReplSet done...';
        wait"

  nats:
    image: nats:2.6-alpine

  traefik:
    image: traefik:v3.6.6
    command:
      - --providers.docker=true
      - '--serverstransport.maxidleconnsperhost=-1'
    ports:
      - 3000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
